name: Build Binaries

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller (Linux)
      if: runner.os == 'Linux'
      run: |
        pyinstaller --name Amnezia-Web-Panel-Linux \
          --add-data "static:static" \
          --add-data "templates:templates" \
          --add-data "translations:translations" \
          --hidden-import uvicorn \
          --hidden-import fastapi \
          --clean \
          -y \
          -F app.py

    - name: Build with PyInstaller (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --name Amnezia-Web-Panel-Windows `
          --add-data "static;static" `
          --add-data "templates;templates" `
          --add-data "translations;translations" `
          --hidden-import uvicorn `
          --hidden-import fastapi `
          --clean `
          -y `
          -F app.py

    - name: Build with PyInstaller (macOS)
      if: runner.os == 'macOS'
      run: |
        pyinstaller --name Amnezia-Web-Panel-macOS \
          --add-data "static:static" \
          --add-data "templates:templates" \
          --add-data "translations:translations" \
          --hidden-import uvicorn \
          --hidden-import fastapi \
          --clean \
          -y \
          -F app.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Amnezia-Web-Panel-${{ runner.os }}
        path: dist/Amnezia-Web-Panel-*
